baseurl: "/via-it-literacy-website"

exclude: ["resources", "scripts"]

# plugins
plugins:
  - jekyll-polyglot

# markdown: Pandoc

# collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:name

# i18n
languages: ["en", "zh", "hi"]
default_lang: "en"
exclude_from_localization: ["js", "css", "public"]
parallel_localization: true

sass:
  sourcemap: never
